#!/bin/bash

if [[ $1 = -h ]] || [[ $1 = --help ]] || [[ $# = 0 ]]; then
   cat <<EOF
Usage: furbishtex [files]

Configuration:
    Furbishtex will search both /usr/share/furbishtex
    and \$HOME/.furbishtex and pass all the files from
    these directories on to sed to apply to the files
    given from the command line.
    Furbishtex is thus configured in sed's script
    language.

EOF
	exit 0
fi

files="$@"

if ls /usr/lib/furbishtex/* &>/dev/null; then
	conf=($(ls /usr/lib/furbishtex/*))
fi
if ls $HOME/.furbishtex/* &>/dev/null; then
	conf=($conf $(ls $HOME/.furbishtex/*))
fi

if [[ $conf = "" ]]; then
	echo "ERROR: No configuration files found"
	echo "   Please verify that either /usr/share/furbishtex or"
	echo "   $HOME/.furbishtex contain at least one file."
	exit 1
fi

for idx in "${!conf[@]}"; do

	scripts="$scripts -f ${conf[$idx]}"

done

sed -i $scripts $files

